data_params:
  path_result: ../data/lstm_crf/result.txt
  path_test: ../data/lstm_crf/test.txt
  path_train: ../data/lstm_crf/train.txt
  sep: table
  voc_params:
    char: {min_count: 1, path: null}
    f1: {min_count: 1, path: ../data/lstm_crf/train_test_word2ids.pkl}
    f2: {min_count: 1, path: null}
    label: {min_count: 0, path: ../data/lstm_crf/train_test_tag2ids.pkl}
model: lstm_crf
model_params:
  batch_size: 128
  bilstm_params: {num_layers: 1, num_units: 256, rnn_dropout: 0.2}
  clip: 10
  conv_dropout: 0.2
  conv_filter_len_list: [1, 2, 3, 4, 5]
  conv_filter_size_list: [8, 8, 8, 8, 8]
  dev_size: 0.1
  dropout_rate: 0.3
  embed_params:
    char:
      dropout_rate: null
      path: null
      path_pre_train: null
      shape: [null, null]
    f1:
      dropout_rate: 0.3
      path: ../data/lstm_crf/f1_embed.mat.pkl
      path_pre_train: ../data/word2vec.txt
      shape: [4685, 256]
    f2:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [null, null]
  feature_names: [f1]
  l2_rate: 0.001
  learning_rate: 0.00005
  max_patience: 5
  nb_classes: 4
  nb_epoch: 1000
  path_model: ../model/lstm_crf/model
  rnn_unit: lstm
  sequence_len_pt: 95
  sequence_length: 128
  use_char_feature: false
  use_crf: true
  word_len_pt: 95
  word_length: 11
unknow_word: unk
